language: c

compiler:
  - gcc

before_install:
  - sudo apt-get build-dep arpack
  - sudo apt-get install openmpi-bin

script:
  - ./bootstrap
  - ./configure --enable-mpi
  - make all
  - make check
  - make distcheck
