sudo: false

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin

env:
  - USE_CMAKE=true
  - USE_CMAKE=false

before_script:
  - if [ "$USE_CMAKE" == "true" ]; then mkdir build ; fi
  - if [ "$USE_CMAKE" == "true" ]; then cd build ; fi
  - if [ "$USE_CMAKE" == "true" ]; then cmake .. ; fi

script:
  # CMAKE
  - if [ "$USE_CMAKE" == "true" ]; then make ; fi
  # CONFIGURE
  - if [ "$USE_CMAKE" == "false" ]; then ./bootstrap ; fi
  - if [ "$USE_CMAKE" == "false" ]; then ./configure --enable-mpi ; fi
  - if [ "$USE_CMAKE" == "false" ]; then make all ; fi
  - if [ "$USE_CMAKE" == "false" ]; then make check ; fi
  - if [ "$USE_CMAKE" == "false" ]; then make distcheck ; fi
